name: flutter_tiktok_sdk_example
description: Demonstrates how to use the flutter_tiktok_sdk plugin.
version: 1.0.0
publish_to: "none"
environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  tiktok_sdk_login_share:
    path: ../
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  ph_picker_view_controller: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
