name: tiktok_sdk_login_share
description: A Flutter plugin that lets developers access TikTok's native SDKs in Flutter apps with Dart
version: 0.0.3
homepage: https://github.com/ganlong-2016/tiktok_sdk_v2.git

repository: https://github.com/ganlong-2016/tiktok_sdk_v2.git

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.tofinds.tiktok_sdk_v2
        pluginClass: TiktokSdkV2Plugin
      ios:
        pluginClass: TiktokSdkV2Plugin
